package webserver

import (
	"fmt"
	"io"
	"log"
	"net"
	"net/http"
	"os"
	"path"
	"path/filepath"
	"strings"
	"time"

	"github.com/NHAS/reverse_ssh/internal"
	"github.com/NHAS/reverse_ssh/internal/server/data"
	"github.com/NHAS/reverse_ssh/internal/server/webserver/shellscripts"
	"github.com/NHAS/reverse_ssh/pkg/logger"
	"golang.org/x/crypto/ssh"
)

var (
	DefaultConnectBack    string
	DefaultDownloadScheme string
	defaultFingerPrint    string
	projectRoot           string
	webserverOn           bool
)

func Start(webListener net.Listener, connectBackAddress string, autogeneratedConnectBack bool, projRoot, dataDir string, publicKey ssh.PublicKey, downloadScheme string) {
	projectRoot = projRoot
	DefaultConnectBack = connectBackAddress
	DefaultDownloadScheme = downloadScheme
	if DefaultDownloadScheme == "" {
		DefaultDownloadScheme = "http"
	}
	defaultFingerPrint = internal.FingerprintSHA256Hex(publicKey)

	err := startBuildManager(filepath.Join(dataDir, "cache"))
	if err != nil {
		log.Fatal(err)
	}

	srv := &http.Server{
		ReadTimeout:  60 * time.Second,
		WriteTimeout: 60 * time.Second,
		Handler:      buildAndServe(autogeneratedConnectBack),
	}

	log.Println("Started Web Server")
	webserverOn = true

	log.Fatal(srv.Serve(webListener))

}

func DownloadURL(name string) string {
	return DefaultDownloadScheme + "://" + path.Join(DefaultConnectBack, name)
}

const notFound = `<html>
<head><title>404 Not Found</title></head>
<body>
<center><h1>404 Not Found</h1></center>
<hr><center>nginx</center>
</body>
</html>`

func logDownloadTiming(path, remoteAddr, step string, started time.Time) {
	log.Printf("download timing path=%q remote=%s step=%s elapsed=%s", path, remoteAddr, step, time.Since(started))
}

func buildAndServe(autogeneratedConnectBack bool) http.HandlerFunc {
	return func(w http.ResponseWriter, req *http.Request) {
		started := time.Now()
		path := req.URL.Path
		remoteAddr := req.RemoteAddr

		httpDownloadLog := logger.NewLog(fmt.Sprintf("%s:%q", remoteAddr, req.Host))

		httpDownloadLog.Info("Web Server got hit:  %q", path)
		logDownloadTiming(path, remoteAddr, "handler_enter", started)

		filename := strings.TrimPrefix(path, "/")
		linkExtension := filepath.Ext(filename)

		filenameWithoutExtension := strings.TrimSuffix(filename, linkExtension)

		f, err := data.GetDownload(filename)
		logDownloadTiming(path, remoteAddr, "get_download_exact", started)
		if err != nil {
			f, err = data.GetDownload(filenameWithoutExtension)
			logDownloadTiming(path, remoteAddr, "get_download_stripped", started)
			if err != nil {
				log.Println("could not get: ", filenameWithoutExtension, " err: ", err)
				logDownloadTiming(path, remoteAddr, "not_found_before_write", started)

				w.Header().Set("content-type", "text/html")
				w.Header().Set("server", "nginx")
				w.Header().Set("Connection", "keep-alive")

				w.WriteHeader(http.StatusNotFound)
				w.Write([]byte(notFound))
				logDownloadTiming(path, remoteAddr, "not_found_after_write", started)
				return
			}

			if linkExtension != "" {

				host := DefaultConnectBack
				if autogeneratedConnectBack || f.UseHostHeader {
					host = req.Host
				}

				host, port, err := net.SplitHostPort(host)
				if err != nil {
					host = DefaultConnectBack
					port = "80"

					httpDownloadLog.Info("no port specified in external_address: %s defaulting to: %s", DefaultConnectBack, DefaultConnectBack+":80")
				}
				logDownloadTiming(path, remoteAddr, "template_host_resolved", started)

				output, err := shellscripts.MakeTemplate(shellscripts.Args{
					OS:               f.Goos,
					Arch:             f.Goarch,
					Name:             filenameWithoutExtension,
					Host:             host,
					Port:             port,
					Protocol:         DefaultDownloadScheme,
					WorkingDirectory: f.WorkingDirectory,
				}, linkExtension[1:])
				logDownloadTiming(path, remoteAddr, "template_built", started)
				if err != nil {

					w.Header().Set("content-type", "text/html")
					w.Header().Set("server", "nginx")
					w.Header().Set("Connection", "keep-alive")

					w.WriteHeader(http.StatusNotFound)
					w.Write([]byte(notFound))
					logDownloadTiming(path, remoteAddr, "template_error_after_write", started)
					return
				}

				w.Header().Set("Content-Disposition", "attachment; filename="+filename)
				w.Header().Set("Content-Type", "application/octet-stream")

				w.Write(output)
				logDownloadTiming(path, remoteAddr, "template_after_write", started)
				return
			}
		}

		file, err := os.Open(f.FilePath)
		logDownloadTiming(path, remoteAddr, "binary_opened", started)
		if err != nil {
			httpDownloadLog.Error("failed to open file for http download: %s", err)
			http.Error(w, "Error: "+err.Error(), http.StatusInternalServerError)
			logDownloadTiming(path, remoteAddr, "binary_open_error", started)
			return
		}
		defer file.Close()

		var extension string

		switch f.FileType {
		case "shared-object":
			if f.Goos != "windows" {
				extension = ".so"
			} else if f.Goos == "windows" {
				extension = ".dll"
			}
		case "executable":
			if f.Goos == "windows" {
				extension = ".exe"
			}
		default:

		}

		w.Header().Set("Content-Disposition", "attachment; filename="+strings.TrimSuffix(filename, extension)+extension)
		w.Header().Set("Content-Type", "application/octet-stream")

		io.Copy(w, file)
		logDownloadTiming(path, remoteAddr, "binary_after_copy", started)
	}
}
